//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ_shops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string user_id { get; set; }
        public int bill_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_category { get; set; }
        public decimal product_price { get; set; }
        public string shipping_address { get; set; }
        public string payment__mode { get; set; }
    }
}
